apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: node-test
        image: ronvincentorg.azurecr.io/test_node:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 3000
          name: node-test